c32af796-f056-4273-b498-61040c7b4b15:
  prompt:
  - 0
  - c32af796-f056-4273-b498-61040c7b4b15
  - '5':
      inputs:
        width: 512
        height: 512
        batch_size: 1
      class_type: EmptyLatentImage
      meta:
        title: Empty Latent Image
    '6':
      inputs:
        text: beautiful landscape scenery glass bottle with a galaxy inside cute fennec
          fox snow HDR sunset
        clip:
        - '20'
        - 1
      class_type: CLIPTextEncode
      meta:
        title: CLIP Text Encode (Prompt)
    '7':
      inputs:
        text: text, watermark
        clip:
        - '20'
        - 1
      class_type: CLIPTextEncode
      meta:
        title: CLIP Text Encode (Prompt)
    '8':
      inputs:
        samples:
        - '13'
        - 0
        vae:
        - '20'
        - 2
      class_type: VAEDecode
      meta:
        title: VAE Decode
    '13':
      inputs:
        add_noise: true
        noise_seed: 0
        cfg: 1.0
        model:
        - '20'
        - 0
        positive:
        - '6'
        - 0
        negative:
        - '7'
        - 0
        sampler:
        - '14'
        - 0
        sigmas:
        - '22'
        - 0
        latent_image:
        - '5'
        - 0
      class_type: SamplerCustom
      meta:
        title: SamplerCustom
    '14':
      inputs:
        sampler_name: euler_ancestral
      class_type: KSamplerSelect
      meta:
        title: KSamplerSelect
    '20':
      inputs:
        ckpt_name: sd_xl_turbo_1.0_fp16.safetensors
      class_type: CheckpointLoaderSimple
      meta:
        title: Load Checkpoint
    '22':
      inputs:
        steps: 1
        denoise: 1.0
        model:
        - '20'
        - 0
      class_type: SDTurboScheduler
      meta:
        title: SDTurboScheduler
    '25':
      inputs:
        images:
        - '8'
        - 0
      class_type: PreviewImage
      meta:
        title: Preview Image
  - {}
  - - '25'
  outputs:
    '25':
      images:
      - filename: ComfyUI_temp_gvruv_00001_.png
        subfolder: ''
        type: temp
  status:
    status_str: success
    completed: true
    messages:
    - - execution_start
      - prompt_id: c32af796-f056-4273-b498-61040c7b4b15
    - - execution_cached
      - nodes: []
        prompt_id: c32af796-f056-4273-b498-61040c7b4b15
